services:
  db:
    image: postgres:15-alpine
    container_name: techstars_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: scrapper
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: techstars_api
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:postgresql://db:5432/scrapper
      - DB_USER=root
      - DB_PASSWORD=root
    depends_on:
      - db

volumes:
  postgres_data: