spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/techstars_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:your_password}
  jpa:
    hibernate:
      ddl-auto: update

springdoc:
  swagger-ui:
    path: /swagger-ui.html

app:
  scraper:
    api-url: "https://api.getro.com/api/v2/collections/89/search/jobs"
    cron: "0 0 3 * * ?"
    batch-size: 50